name: Pandaz
main: Zinkil\Pandaz\Core
version: 2.0.0
api: 3.0.0
author: Zinkil
description: "The Offical Core Of Pandaz MCPE Practice Server."

permissions:
  Pandaz.command.fly:
    description: 'Permission to enable or disable fly.'
    default: op
    Pandaz.command.disguise:
    description: 'Permission to disguise.'
    default: op
    Pandaz.access.staffchat:
    description: 'Permission to chat in the staff chat.'
    default: op
    Pandaz.command.gm:
    description: 'Permission to change player gamemode.'
    default: op
    Pandaz.can.build:
    description: 'Permission to build in the server.'
    default: op
    Pandaz.can.break:
    description: 'Permission to break blocks in the server.'
    default: op
    Pandaz.command.staff:
    description: 'Permission to enable or disable staff mode.'
    default: op
    Pandaz.command.vanish:
    description: 'Permission to enable or disable vanish.'
    default: op
    Pandaz.command.tban:
    description: 'Permission to temporarily ban players.'
    default: op
    Pandaz.command.mute:
    description: 'Permission to temporarily mute players.'
    default: op
    Pandaz.command.freeze:
    description: 'Permission to freeze players.'
    default: op
    Pandaz.staff.cheatalerts:
    description: 'Permission to receive anticheat alerts.'
    default: op
    Pandaz.command.who:
    description: 'Permission to get player info.'
    default: op
    Pandaz.command.alias:
    description: 'Permission to get player alt accounts.'
    default: op
    Pandaz.staff.notifications:
    description: 'Permission to receive notifications of server acts.'
    default: op
    Pandaz.command.pban:
    description: 'Permission to permenantly ban players.'
    default: op